import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import invitationsRouter from "./invitations";
import usersRouter from "./users";
import geoRouter from "./geo";
import centersRouter from "./centers";
import academicsRouter from "./academics";
import academicYearsRouter from "./academicYears";
import fctRouter from "./fct";
import surveysRouter from "./surveys";
import eventsRouter from "./events";
import aiRouter from "./ai";
import dashboardRouter from "./dashboard";
import settingsRouter from "./settings";
import backupRouter from "./backup";
import messagingRouter from "./messaging";
import mobileRouter from "./mobile";
import storageRouter from "./storage";
import documentFormsRouter from "./documentForms";
import feedbackRouter from "./feedback";
import meetingsRouter from "./meetings";
import forumsRouter from "./forums";
import oidcRouter from "./oidc";
import collabRouter from "./collab";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(invitationsRouter);
router.use(usersRouter);
router.use(geoRouter);
router.use(centersRouter);
router.use(academicsRouter);
router.use(academicYearsRouter);
router.use(fctRouter);
router.use(surveysRouter);
router.use(eventsRouter);
router.use(aiRouter);
router.use(dashboardRouter);
router.use(settingsRouter);
router.use(backupRouter);
router.use(messagingRouter);
router.use(mobileRouter);
router.use(storageRouter);
router.use(documentFormsRouter);
router.use(feedbackRouter);
router.use(meetingsRouter);
router.use(forumsRouter);
router.use(oidcRouter);
router.use(collabRouter);

export default router;
